# Generated by Django 4.0.3 on 2022-06-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolshoi_cast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.CharField(default=50, max_length=1000, null=True),
        ),
    ]
