# Generated by Django 4.0.3 on 2022-06-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolshoi_cast', '0002_artist_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.CharField(default=50, max_length=20000, null=True),
        ),
    ]
