# Generated by Django 4.0.3 on 2022-06-06 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolshoi_cast', '0003_alter_artist_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='sphere',
            new_name='realm',
        ),
    ]
