# Generated by Django 4.0.3 on 2022-06-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolshoi_cast', '0005_alter_artist_realm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='position',
            field=models.CharField(choices=[('Балерины', 'Балерины'), ('Премьеры', 'Премьеры'), ('Ведущие солистки', 'Ведущие солистки'), ('Ведущие солисты', 'Ведущие солисты'), ('Первые солистки', 'Первые солистки'), ('Первые солисты', 'Первые солисты'), ('Солистки', 'Солистки'), ('Солисты', 'Солисты'), ('Сопрано', 'Сопрано'), ('Меццо-сопрано', 'Меццо-сопрано'), ('Теноры', 'Теноры'), ('Баритоны', 'Баритоны'), ('Бассы', 'Бассы'), ('Дирижеры', 'Дирижеры'), ('Хор', 'Хор')], default='Балерины', max_length=40),
        ),
        migrations.AlterField(
            model_name='artist',
            name='realm',
            field=models.CharField(choices=[('Балет', 'Балет'), ('Опера', 'Опера'), ('Оркестр', 'Оркестр')], default='Балет', max_length=40),
        ),
    ]
